-- hackerrank.com/challenges/weather-observation-station-5

/*
Enter your query here.
*/
SELECT CITY, LENGTH(CITY) FROM STATION WHERE LENGTH(CITY) = (select LENGTH(CITY) FROM STATION ORDER BY LENGTH(CITY) LIMIT 1) ORDER BY CITY LIMIT 1;
SELECT CITY, LENGTH(CITY) FROM STATION WHERE LENGTH(CITY) = (select LENGTH(CITY) FROM STATION ORDER BY LENGTH(CITY) DESC LIMIT 1) ORDER BY CITY LIMIT 1;
